version: "3.7"

services:

  flask:
    build: ./apiserver
    container_name: apiserver
    restart: always
    volumes:
      - type: bind
        source: ./logs
        target: /logs
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1/healthcheck"]
      interval: 1m
      timeout: 10s
      retries: 3